GPS_RECEF=[];
BDS_RECEF=[];
QZSS_RECEF=[];
for i=1:1440
    GPS_RECEF = [GPS_RECEF, ECI2ECEF_DCM(GPS.t(i)) * GPS.ECI(i,:)'];
    BDS_RECEF = [BDS_RECEF, ECI2ECEF_DCM(BDS.t(i)) * BDS.ECI(i,:)'];
    QZSS_RECEF = [QZSS_RECEF, ECI2ECEF_DCM(QZSS.t(i)) * QZSS.ECI(i,:)'];
end
GPS.RECEF = GPS_RECEF';
BDS.RECEF = BDS_RECEF';
QZSS.RECEF = QZSS_RECEF';
